version: '3'
services:
  account-service:
    build: ~/account-service
    ports:
      - "3000:3000"
    networks:
      - pdf-labs-net
    environment:
      - NODE_ENV=development
      - MONGO_URI=YOUR-DATABASE-URL
      - JWT_SECRET=YOUR-SECRET

  home-service:
    build: ~/home-service
    ports:
      - "4000:4000"
    networks:
      - pdf-labs-net
    environment:
      - NODE_ENV=development
      - MONGO_URI=YOUR-DATABASE-URL
      - JWT_SECRET=YOUR-SECRET

  profile-service:
    build: ~/profile-service
    ports:
      - "4500:4500"
    networks:
      - pdf-labs-net
    environment:
      - NODE_ENV=development
      - MONGO_URI=YOUR-DATABASE-URL
      - JWT_SECRET=YOUR-SECRET

  logout-service:
    build: ~/logout-service
    ports:
      - "5000:5000"
    networks:
      - pdf-labs-net
    environment:
      - NODE_ENV=development
      - MONGO_URI=YOUR-DATABASE-URL
      - JWT_SECRET=YOUR-SECRET

  tools-service:
    build: ~/tools-service
    ports:
      - "3500:3500"
    networks:
      - pdf-labs-net
    environment:
      - NODE_ENV=development
      - MONGO_URI=YOUR-DATABSE-URL
      - JWT_SECRET=YOUR-SECRET

  pdf-to-image-service:
    build: ~/pdf-to-image-service
    ports:
      - "5500:5500"
    networks:
      - pdf-labs-net
    environment:
      - NODE_ENV=development
      - MONGO_URI=YOUR-DATABASE-URL
      - JWT_SECRET=YOUR-SECRET

networks:
  pdf-labs-net:
    driver: bridge
