name: Branch CI

on:
  push:
  pull_request:

permissions:
  contents: write
  packages: write   # needed for GHCR push

jobs:
  run-ci:
    uses: Godfrey22152/MICROSERVICE-PDF-LABS/.github/workflows/Shared-CI.yml@main
    secrets: inherit
