name: Branch CI

on:
  push:
  pull_request:
  
permissions:
  contents: read
  packages: write        # needed for GHCR push
  checks: write          # needed for Allure
  pull-requests: write   # needed for PR comments

jobs:
  run-ci:
    uses: Godfrey22152/MICROSERVICE-PDF-LABS/.github/workflows/Shared-CI.yml@main
    secrets: inherit
